### ISSUE TITLE
Loading Morph Controller (ver2) crashes Ardour

### ISSUE THREAD

**Issue by eventual-recluse** [rrastgoufard/Morph_Ardour#1]
Hi! This plugin looks incredibly useful, but it crashes Ardour when I try to load Morph Controller (ver2).

I think the crash happens when the draw_target function is called, possibly at     local plugin id = math.floor(ctrl[ctrl_pid])

Error message from the terminal is:

ardour-8.6.0: ../libs/lua/LuaBridge/detail/CFunctions.h:1166: static int luabridge::CFunc::array_index(lua_State*) [with T = float; lua_state = lua_state]: Assertion `index > 0' failed.

**Comment by rrastgoufard** [comment]
Hi there!  Thanks for opening this issue!  

Sadly, I can't replicate it...  I have been using it extensively in ardour 8.2, so I thought maybe something happened between that version and the latest 8.6 release.  But after updating to 8.6, my existing projects using the Morph Controller still work just fine as does creating an empty session and adding the Morph Controller and/or Locator.  

If you have any more clues, let me know and I will try to track down the issue.

**Comment by rrastgoufard** [comment]
Wait wait wait!  I can reproduce the problem!  It worked fine for me on 8.6's demo version, but it fails in exactly the way you described when I compile 8.6 myself.  I'll take care of this soon enough!

Thanks for the heads ups!

> Error message from the terminal is:
> 
> ardour-8.6.0: ../libs/lua/LuaBridge/detail/CFunctions.h:1166: static int luabridge::CFunc::array_index(lua_State*) [with T = float; lua_state = lua_state]: Assertion `index > 0' failed.

**Comment by eventual-recluse** [comment]
Ah, yes, I compiled Ardour myself - I didn't realise it would make a difference though

Thanks for looking into it!

**Comment by rrastgoufard** [comment]
I just pushed a quick fix.  Lemme know if it works for you!

**Comment by eventual-recluse** [comment]
Just tried the updated version and it's working now. Thank you! This plugin is fantastic and adds some essential functionality to Ardour. This is great! Thanks again

**Comment by rrastgoufard** [comment]
Yay!  Glad it worked, and I appreciate the kind words!  <3
